### ISSUE TITLE
SSL handshake error in Velux component

### ISSUE THREAD

**Issue by pergolafabio** [pawlizio/my_velux#1]
creating issue here , follow-up of this issue 👍 
https://github.com/home-assistant/core/issues/34844

05/08/2020 , i installed custom component, at this moment no error ion Restart HA, and state is properly loaded

**Comment by pawlizio** [comment]
With regards to:  
"question, should HA fail upon start again, for some reason, the reboot feature is useless? am i correct ?"

Yes, if you cannot establish a connection due to SSL handshake error you are not able to reboot KLF200. So it would be better to reboot the gateway in advance as long as you have a connection. I tried different things, also a periodical reboot. However sometimes I still had a frozen KLF.

Therefore I tried some adjustments which you can check here: https://github.com/Julius2342/pyvlx/pull/49
First it was looking good, even without any automatic reboot of the KLF. But today after I read that you're going to test my custom component I restarted my HA (without rebooting the KLF) as a test after two days without any issue on the connection and unfortunately I could not establish a connection to KLF. 

So unfortunately at the moment I only see the reboot function as a workaround additional function of my custom component. As soon as @Julius2342 will release the current pyvlx master branch the reboot functionality could be integrated into original velux component as a callable service. Within automation everyone can then create an automation via GUI which lets the KLF reboot on homeassistant_stop event.

Example: 
```
- id: '1596623358540'
  alias: KLF reboot on hass stop event
  description: ''
  trigger:
  - event_data: {}
    event_type: homeassistant_stop
    platform: event
  condition: []
  action:
  - data: {}
    service: my_velux.reboot_gateway
  mode: single
```
In my current custom component I activated this in the code, but that's maybe not a good solution for a workaround.
