### ISSUE TITLE
[Bug?] KLF200 need's to be restarted regularly (every 24-30h) to stay connected.

### ISSUE THREAD

**Issue by jaddel** [pawlizio/my_velux#11]
Hi, thank you very much for providing this integration since the newer firmware is currently not supported by HomeAssistant. 

I currently need to restart the KLF regularly to keep it functional. 
Is there something I could try to make it more reliable and which information would be useful to debug this?

thx jaddel

**Comment by pawlizio** [comment]
Did you try an automation? The integration provides a service which automatically force your KLF to reboot. You can call this service when you shutdown your homeassistant, i.e. during a reboot. Below is the yaml:

```
alias: KLF reboot on hass stop event
description: Reboots the KLF200 in order to avoid SSL Handshake issue
trigger:
  - platform: homeassistant
    event: shutdown
condition: []
action:
  - service: velux.reboot_gateway
mode: single

```

**Comment by jaddel** [comment]
I'm already using that automation to force a reboot when HA reboots. 

> Are your problems only if you reboot home assistant or do you loose also the connection without rebooting?

I'm loosing the connection without rebooting.

**Comment by pawlizio** [comment]
Hmm... I don't have such problems. Maybe you can try to add another automation which periodically force the KLF to reboot. How often this happens?

**Comment by jaddel** [comment]
I'll give it a try and otherwise connect a smart plug as a workaround for now to force a reboot every 24h. :sweat_smile:

It currently happens almost every day.

**Comment by pawlizio** [comment]
What kind of devices are in between home assistant ul and klf? Do you use a switch or are they connected through your router? What type of router you use? 

Maybe try another setup, like connect them via switch, if they are now connected through your router.

**Comment by jaddel** [comment]
Thx for the suggestion, I'll give it a try and report back.

They are currently connected via a FRITZ!Box 7590.

**Comment by rohrsh** [comment]
The reboot idea isn't ideal
1. It doesn't help you once your KLF is already unresponsive
2. Home Assistant's on-reboot functionality is broken for some users, including me --> https://community.home-assistant.io/t/home-assistant-stop-automation-not-working/231384

**Comment by neildsb** [comment]
2022.5 my KLF gateway has been stable for ~4 days (only just installed), this morning it was not responsive, added a smart plug to reboot, what time period should I set 24hr - 48hr? setup - all devices are connected on a L2 VLAN via a few  switches. on a side note are Velux updating the FW regularly?

**Comment by rohrsh** [comment]
Yes, the power cycle is the only answer for me. 

You could try an automation like this: 

``` 
alias: POE cycle Velux if a blind is unavailable - check once each hour
trigger:
  - platform: time_pattern
    minutes: '0'
condition:
  - condition: state
    entity_id: cover.ensuite_blind
    state: unavailable
action:
  - service: script.poe_cycle_velux

**Comment by neildsb** [comment]
thanks for the replies, i have added a state 'unavailable' in my node red to power cycle the plug

![image](https://user-images.githubusercontent.com/91122872/153748591-b2e512d2-f3e9-4f74-b81e-0bcfb5341877.png)

**Comment by neildsb** [comment]
> Yes, the power cycle is the only answer for me.
> 
> You could try an automation like this:
> 
> ```
> alias: POE cycle Velux if a blind is unavailable - check once each hour
> trigger:
>   - platform: time_pattern
>     minutes: '0'
> condition:
>   - condition: state
>     entity_id: cover.ensuite_blind
>     state: unavailable
> action:
>   - service: script.poe_cycle_velux
> ```

one quick question, how often does HA poll the KLF’s state to determine if its unavailable? i have disconnected the Ethernet cable and checking the dev tools and it still reports open….ie the last state

**Comment by pawlizio** [comment]
With release 2.2 I've added a sensor which increments with each new established connection to KLF200. The sensor will be reset on each HA restart. However you can use this sensor in order to try some workarounds to fix your issue. In the below example you can reboot KLF200 on each second connection which is established between HA and KLF200. 

```
alias: Reboot KLF200 every second connection
trigger:
  - platform: state
    entity_id: sensor.klf200_connection_counter
condition:
  - condition: template
    value_template: >-
      {{states('sensor.klf200_connection_counter') | float(default = 1) % 2 == 0}}
action:
  - service: velux.reboot_gateway
    data: {}
```

Finally I'm not sure if this will help, but you can try.

**Comment by pawlizio** [comment]
However may you can share the sensor value once the KLF becomes unresponsive. I'd like to understand how many times Home Assistant can reconnect to KLF200 before it becomes unresponsive.

**Comment by neildsb** [comment]
I raised a ticket with Velux, and received the following -

Unfortunately, we are unable assist in debugging the API interface for KLF 200. 
We can only ask that you refer to the documentation on https://www.velux.com/klf200 and what can be found on various web forums.
On below documentation, this is describing the TCP/IP connection. If the socket is not used for more than 15 minutes, it will automatically close down the connection.
 
![image](https://user-images.githubusercontent.com/91122872/154311090-06ff48b3-1811-44cf-8b1b-2bdd7c37d151.png)

**Comment by pawlizio** [comment]
Finally the KLF200 keeps unresponsive even after 15 minutes, that seems to be a bug. However I assume the problem is mainly caused by lost connections. Does someone tried the new version with the connections counter sensor? I would like to know the sensor value in case the KLF200 becomes unresponsive. I'm a bit worried that the bug is becoming a problem if you have some connection interruptions caused by FritzBox or similar Routers. In my case I use a separate Switch, not a Router between HA and KLF200 and I don't have any connection looses.

**Comment by neildsb** [comment]
I have only one connection counter increment, but have rebooted HA a few times for other reasons, I have two switches (Meraki and Netgear) between the KLF and HA over one vlan, via a trunk, my router is upstream....I will try not to reboot for a few days and report back

**Comment by pawlizio** [comment]
But have you configured the automation to force an KLF200 reboot, before you stop/reboot HA?

Like this:

```
alias: KLF reboot on hass stop event
description: Reboots the KLF200 in order to avoid SSL Handshake issue
trigger:
  - platform: homeassistant
    event: shutdown
condition: []
action:
  - service: velux.reboot_gateway
    data: {}
mode: single
```
